[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "geochange"
version = "0.1.0"
description = "Detection automatique des changements entre deux versions de donnees geographiques"
dependencies = [
    "geopandas"
]

[tool.setuptools.packages.find]
where = ["src"]